spring:
  application:
    name: TacoCloudApp
  thymeleaf:
    cache: false
  cassandra:
    keyspace-name: tacocloud
    contact-points: localhost # Or the actual IP addresses of your Cassandra nodes, e.g., "192.168.1.10,192.168.1.11"
    port: 9042 # This is the default port, but good to include for clarity
    local-datacenter: datacenter1
    schema-action: create-if-not-exists
