spring:
  main:
    allow-circular-references: true
  flyway:
    depends-on: entityManagerFactory
    enabled: true
    baseline-on-migrate: true # Good for existing databases
  application:
    name: TacoCloudApp
  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:h2:file:./data/tacocloud.db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 842664503797-rfbau6o4nfuf50vjvqoc07r5epqtkkha.apps.googleusercontent.com
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET} # Optional placeholder
            scope: openid,profile,email
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:/Users/robertkalna/dev/java/spring/learning/taco_cloud_app_resources/keystores/taco_cloud_keystores.p12
    key-alias: "localhost"
    key-store-password: "${TACO_CLOUD_APP_KEYSTORE_PASSWORD}"
    key-password: "${TACO_CLOUD_APP_KEYSTORE_PASSWORD}"
logging:
  file:
    name: /tmp/logs/TacoCloud.log
  level:
    eu:
      kalnarapps:
        TacoCloudApp:
          controllers: debug
taco:
  orders:
    pageSize: 10


---
spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    eu:
      kalnarapps:
        TacoCloudApp:
          controllers: warn
server:
  port: 443
